dbt_lab08_project:
  target: prod
  outputs:
    prod:
      dbname: lab08_db
      host: 146.185.211.176
      pass: fhjr5-Ytuj&j009
      port: 5433
      schema: mart2
      threads: 4
      type: postgres
      user: admin