dbt_lab08_project:
  target: prod
  outputs:
    prod:
      type: postgres
      host: ${POSTGRES_LAB8_HOST}
      user: ${POSTGRES_LAB8_USER}
      password: ${POSTGRES_LAB8_PASSWORD}
      dbname: ${POSTGRES_LAB8_DB}
      schema: ods
      threads: 4
      port: 5433