services:

  postgres:
    image: "postgres:16.3"
    container_name: "postgres"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow-webserver:
    image: arinaexpy/project_lab08:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__WEBSERVER__SECRET_KEY=mysecret
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags/repo/dags
      - PYTHONPATH=/opt/airflow/dags/repo
    volumes:
      - dags:/opt/airflow/dags
      - ./airflow_logs:/usr/local/airflow/logs
      - ./dbt:/dbt
    env_file:
      - .env
    ports:
      - "8080:8080"
    entrypoint: airflow webserver

  airflow-scheduler:
    image: arinaexpy/project_lab08:latest
    restart: always
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags/repo/dags
      - PYTHONPATH=/opt/airflow/dags/repo
    env_file:
      - .env
    volumes:
      - dags:/opt/airflow/dags
      - ./airflow_logs:/usr/local/airflow/logs
      - ./dbt:/dbt
    entrypoint: airflow scheduler

  airflow-init:
    image: arinaexpy/project_lab08:latest
    depends_on:
      - postgres
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags/repo/dags
      - PYTHONPATH=/opt/airflow/dags/repo
      - POSTGRES_LAB8_USER=${POSTGRES_LAB8_USER}
      - POSTGRES_LAB8_PASSWORD=${POSTGRES_LAB8_PASSWORD}
      - POSTGRES_LAB8_HOST=${POSTGRES_LAB8_HOST}
      - POSTGRES_LAB8_DB=${POSTGRES_LAB8_DB}
      - S3_YANDEX_ACCESS_KEY_ID=${S3_YANDEX_ACCESS_KEY_ID}
      - S3_YANDEX_SECRET_ACCESS_KEY=${S3_YANDEX_SECRET_ACCESS_KEY}
      - AIRFLOW_USER=${AIRFLOW_USER}
      - AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - dags:/opt/airflow/dags
      - ./airflow_logs:/usr/local/airflow/logs
      - ./dbt:/dbt
    env_file:
      - .env
    entrypoint: /entrypoint.sh

  gitsync:
    image: k8s.gcr.io/git-sync/git-sync:v3.6.2
    user: "0:0"
    environment:
      - GIT_SYNC_REPO=${GIT_REPO}
      - GIT_SYNC_BRANCH=${GIT_BRANCH}
      - GIT_SYNC_ROOT=/git
      - GIT_SYNC_DEST=repo 
      - GIT_SYNC_WAIT=10
      - GIT_SYNC_USERNAME=${GIT_USERNAME}
      - GIT_SYNC_PASSWORD=${GIT_PASSWORD}
    volumes:
      - dags:/git 

  dbt-docs:
    image: arinaexpy/dbt_lab08:latest
    command: dbt docs serve --host 0.0.0.0 --port 8088
    ports:
      - "8088:8088"
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      - airflow-scheduler
    
volumes:
  postgres_data:
  dags: